version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: citruscms_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - redis
    networks: [citruscms]

  webserver:
    image: nginx:alpine
    container_name: citruscms_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks: [citruscms]

  db:
    image: mysql:8.0
    container_name: citruscms_db
    environment:
      MYSQL_DATABASE: citruscms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: citruscms
      MYSQL_PASSWORD: citruscms
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks: [citruscms]

  redis:
    image: redis:alpine
    container_name: citruscms_redis
    ports:
      - "6379:6379"
    networks: [citruscms]

networks:
  citruscms:
    driver: bridge

volumes:
  dbdata:
    driver: local
